name: test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GATSBY_SANITY_PROJECT_ID: ${{ secrets.GATSBY_SANITY_PROJECT_ID }}
      GATSBY_SANITY_DATASET: ${{ secrets.GATSBY_SANITY_DATASET }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.11'
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci
      - run: npm run build
